### ISSUE TITLE
error writing json file to postgis db

### ISSUE THREAD

**Issue by maning** [mbasa/dostSensor#3]
java -jar /home/ubuntu/dostsensor/dostSensor.jar http://noah.dost.gov.ph/latest/download/station_all
org.apache.wink.json4j.JSONException: Unexpected character: [<] while scanning JSON String for JSON type.  Invalid JSON.
    at org.apache.wink.json4j.JSON.parse(JSON.java:127)
    at org.apache.wink.json4j.JSON.parse(JSON.java:58)
    at org.apache.wink.json4j.JSON.parse(JSON.java:193)
    at org.apache.wink.json4j.JSON.parse(JSON.java:212)
    at org.georepublic.json.JsonProc.getJsonData(JsonProc.java:34)
    at org.georepublic.main.GetFloodData.main(GetFloodData.java:23)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)

**Comment by maning** [comment]
The current /station_all service added a javascript redirect to the link breaking access outside the browser:

```
curl http://noah.dost.gov.ph/latest/download/station_all/
<html><head><title>Request Rejected</title></head><body>The requested URL was rejected. Please consult with your administrator.<br><br>Your support ID is: 16459108203546971202<br><br><a href='javascript:history.back();'>[Go Back]</a></body></html>
```
